/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Yuki (https://sketchfab.com/SHLER)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/appearance-effect-light-beam-fd37b7bec4ca48a8b6539dc4048787cf
Title: 中国风底纹出场特效光圈Appearance effect light beam
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/diwen.glb')
  const { actions } = useAnimations(animations, group)

  // 监听 isScattered 属性变化
  useEffect(() => {
    const animation = actions["Take 001"]
    if (!animation) return

    if (props.isScattered) {
      animation.paused = true
      animation.stop()
      group.current.traverse((child) => {
        if (child.isMesh) {
          child.visible = false
        }
      })
      
    } else {
      animation.reset().play()
      group.current.traverse((child) => {
        if (child.isMesh) {
          child.visible = true
        }
      })
    }
  }, [props.isScattered, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.685}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Effect_2">
                <group name="1_3" rotation={[0, 0.812, 0]} scale={0.148}>
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="2_4" rotation={[0, -0.812, 0]} scale={0.044}>
                  <mesh
                    name="Object_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials.material_1}
                  />
                </group>
                <group name="3_5" position={[0, 0.083, 0]} scale={0.072}>
                  <mesh
                    name="Object_9"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.material_2}
                  />
                </group>
                <group
                  name="5_6"
                  position={[0, 0.349, 0]}
                  rotation={[-1.527, 0, 0]}
                  scale={[0.107, 0.066, 0.066]}>
                  <mesh
                    name="Object_11"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.material_3}
                  />
                </group>
                <group
                  name="liang_7"
                  position={[0.242, 0.434, -0.038]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_13"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(1)_8"
                  position={[0.154, 0.49, -0.112]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_15"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(2)_9"
                  position={[0.088, 0.322, -0.186]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.031, 0.147, 0.031]}>
                  <mesh
                    name="Object_17"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(3)_10"
                  position={[0.01, 0.65, -0.215]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_19"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(4)_11"
                  position={[-0.053, 0.65, -0.193]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_21"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(5)_12"
                  position={[-0.123, 0.505, -0.168]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.018, 0.087, 0.018]}>
                  <mesh
                    name="Object_23"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(6)_13"
                  position={[-0.166, 0.742, -0.113]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_25"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(7)_14"
                  position={[-0.211, 0.436, -0.048]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_27"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(8)_15"
                  position={[-0.264, 0.374, 0.042]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.002, 0.013, 0.002]}>
                  <mesh
                    name="Object_29"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_29.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(9)_16"
                  position={[-0.241, 0.65, 0.101]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_31"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(10)_17"
                  position={[-0.153, 0.65, 0.203]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_33"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(11)_18"
                  position={[-0.085, 0.65, 0.225]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_35"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_35.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(12)_19"
                  position={[-0.028, 0.735, 0.239]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_37"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(13)_20"
                  position={[0.068, 0.65, 0.229]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_39"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_39.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(14)_21"
                  position={[0.121, 0.65, 0.209]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_41"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_41.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(15)_22"
                  position={[0.178, 0.533, 0.131]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_43"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_43.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(16)_23"
                  position={[0.205, 0.566, 0.08]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_45"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_45.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(17)_24"
                  position={[-0.106, 0.773, -0.196]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_47"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_47.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(18)_25"
                  position={[-0.149, 0.047, -0.124]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.053, 0.25, 0.053]}>
                  <mesh
                    name="Object_49"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_49.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(19)_26"
                  position={[0.037, 0.569, -0.179]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_51"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_51.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(20)_27"
                  position={[0.198, 0.355, 0.144]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_53"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_53.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(21)_28"
                  position={[0.188, 0.407, 0.03]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={[0.07, 0.043, 0.07]}>
                  <mesh
                    name="Object_55"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_55.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(22)_29"
                  position={[0.194, 0.5, -0.069]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_57"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_57.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(23)_30"
                  position={[0.159, 0.563, -0.145]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={[0.07, 0.065, 0.07]}>
                  <mesh
                    name="Object_59"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_59.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(24)_31"
                  position={[0.099, 0.571, -0.174]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_61"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_61.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(25)_32"
                  position={[0.032, 0.571, -0.206]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_63"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_63.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(26)_33"
                  position={[-0.037, 0.663, -0.197]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_65"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_65.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(27)_34"
                  position={[-0.115, 0.332, -0.183]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={[0.099, 0.192, 0.099]}>
                  <mesh
                    name="Object_67"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_67.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(28)_35"
                  position={[-0.216, 0.308, -0.157]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_69"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_69.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(29)_36"
                  position={[-0.242, 0.571, -0.099]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_71"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_71.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(30)_37"
                  position={[-0.252, 0.571, 0.035]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_73"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_73.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(31)_38"
                  position={[-0.219, 0.571, 0.099]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_75"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_75.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(32)_39"
                  position={[-0.189, 0.656, 0.149]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_77"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_77.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(33)_40"
                  position={[-0.114, 0.571, 0.21]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_79"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_79.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(34)_41"
                  position={[-0.062, 0.513, 0.233]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={[0.07, 0.258, 0.07]}>
                  <mesh
                    name="Object_81"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_81.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(35)_42"
                  position={[0.033, 0.454, 0.218]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_83"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_83.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(36)_43"
                  position={[0.088, 0.475, 0.202]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={[0.07, 0.081, 0.07]}>
                  <mesh
                    name="Object_85"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_85.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(37)_44"
                  position={[0.064, 0.694, -0.214]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_87"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_87.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(38)_45"
                  position={[-0.018, 0.424, -0.193]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_89"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_89.geometry}
                    material={materials.material_4}
                  />
                </group>
                <group
                  name="liang_(39)_46"
                  position={[0.153, 0.49, -0.1]}
                  rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                  scale={0}>
                  <mesh
                    name="Object_91"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_91.geometry}
                    material={materials.material_4}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/diwen.glb')

