/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Prasin Shrestha (https://sketchfab.com/prasinShrestha)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/chinese-fantasy06-6490aaa7920f4ea3aa13f41f24d8743c
Title: Chinese Fantasy06
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/chinese_fantasy06.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-7.584, 1.65, -1.731]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Red_PlainWood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Dark_Wood}
        />
      </group>
      <group
        position={[-33.12, 14.082, 7.75]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={1.617}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Windows01_Dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Dark_Wood}
        />
      </group>
      <group
        position={[-33.318, 6.106, -1.652]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[0.989, 1.973, 4.818]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.Bronze_Roof}
        />
      </group>
      <group
        position={[-33.12, 15.319, 7.752]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[1.836, 1.836, 1.644]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.Ornment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[-33.12, 15.319, -11.117]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[1.836, 1.836, 1.644]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.Ornment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[-33.12, 14.082, -11.282]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={1.617}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials.Windows01_Dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.Dark_Wood}
        />
      </group>
      <group
        position={[29.138, 30.604, -1.766]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[2.314, 2.773, 2.483]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_36.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_38.geometry}
          material={materials.Ornment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[29.504, 2.197, 17.465]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[1.847, 1.876, 5.77]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.Dark_Wood}
        />
      </group>
      <group
        position={[28.743, 2.25, -21.21]}
        rotation={[0, 0.002, 0]}
        scale={[1.847, 1.876, 5.77]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_47.geometry}
          material={materials.Dark_Wood}
        />
      </group>
      <group
        position={[46.417, 2.25, -2.162]}
        rotation={[0, -1.569, 0]}
        scale={[1.847, 1.876, 5.77]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials.Dark_Wood}
        />
      </group>
      <group
        position={[29.427, 22.319, -1.766]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[2.67, 2.67, 2.98]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[29.379, 16.689, -1.766]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[2.94, 2.807, 3.557]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[29.026, 10.891, -1.356]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[3.036, 3.106, 4.128]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_60.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[29.462, 3.985, -1.759]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[8.181, 3.962, 6.108]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.White_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials.Dark_Wood}
        />
      </group>
      <group
        position={[29.462, 3.985, -1.759]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[8.181, 3.962, 6.108]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials.White_Wall}
        />
      </group>
      <group
        position={[29.462, 3.985, -1.759]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[8.181, 3.962, 6.108]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials.White_Wall}
        />
      </group>
      <group
        position={[29.462, 3.985, -1.759]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[8.181, 3.962, 6.108]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_74.geometry}
          material={materials.White_Wall}
        />
      </group>
      <group
        position={[29.462, 10.248, -1.759]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[8.181, 3.962, 6.108]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_78.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_79.geometry}
          material={materials.White_Wall}
        />
      </group>
      <group
        position={[22.726, 7.987, -1.766]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[1.651, 2.268, 2.502]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_85.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_86.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_87.geometry}
          material={materials.Ornment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_88.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[36.201, 8.349, -1.766]}
        rotation={[0, 0.002, 0]}
        scale={[1.651, 2.268, 2.502]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_90.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_91.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_92.geometry}
          material={materials.Ornment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_93.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[29.138, 7.944, 7.236]}
        rotation={[0, -1.569, 0]}
        scale={[1.25, 1.718, 1.895]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_95.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_96.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_97.geometry}
          material={materials.Ornment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_98.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[29.134, 7.934, -10.488]}
        rotation={[-Math.PI, 1.569, Math.PI]}
        scale={[1.246, 1.713, 1.889]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_100.geometry}
          material={materials.Bronze_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_101.geometry}
          material={materials['Roof.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_102.geometry}
          material={materials.Ornment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_103.geometry}
          material={materials['Roof.000']}
        />
      </group>
      <group
        position={[21.276, 2.448, -1.752]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.978, 2.411, 1.554]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_107.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_108.geometry}
          material={materials.White_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_109.geometry}
          material={materials.Door}
        />
      </group>
      <group
        position={[37.545, 2.448, -1.766]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[4.978, 2.411, 1.554]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_111.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_112.geometry}
          material={materials.White_Wall}
        />
      </group>
      <group
        position={[29.455, 2.448, -12.209]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.978, 2.411, 1.554]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_114.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_115.geometry}
          material={materials.White_Wall}
        />
      </group>
      <group position={[29.469, 2.448, 8.598]} scale={[4.978, 2.411, 1.554]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_117.geometry}
          material={materials.Dark_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_118.geometry}
          material={materials.White_Wall}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Red_PlainWood}
        position={[-7.584, 1.65, -1.731]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Bronze_Roof}
        position={[-33.317, 8.613, -1.652]}
        rotation={[0, 0.002, 0]}
        scale={[2.518, 3.277, 4.891]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Bricks_White}
        position={[-33.014, 0.951, -11.087]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={4.628}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Bricks_White}
        position={[-33.101, 0.951, 7.709]}
        rotation={[-Math.PI, 1.569, -Math.PI]}
        scale={4.628}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.Emission}
        position={[165.891, 50.927, -0.698]}
        rotation={[0, 0, Math.PI / 2]}
        scale={9.121}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_65.geometry}
        material={materials.Windows01}
        position={[29.138, 13.308, -1.766]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.136, 1.458, 1.458]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials.Windows01}
        position={[29.138, 19.571, -1.766]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.136, 1.458, 1.458]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_81.geometry}
        material={materials.Windows02}
        position={[29.462, 3.985, -1.759]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[8.181, 3.962, 6.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_83.geometry}
        material={materials.Dark_Wood}
        position={[29.138, 26.992, -1.602]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[6.262, 0.464, 5.225]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_105.geometry}
        material={materials.Dark_Wood}
        position={[29.427, 22.319, -1.766]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[2.67, 2.67, 2.98]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials.Dark_Wood}
        position={[25.612, 22.911, -7.038]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.429}
      />
    </group>
  )
}

useGLTF.preload('/chinese_fantasy06.glb')
